### PR TITLE
Add auth components  with local storage plugin

### LINKED ISSUE #1: Authenticate a user and save the token in localStorage
Using the **axios** lib, make a `POST` request to API route `/v1/auth/register` with required parameters
 * `first_name`
 * `last_name`
 * `username`
  *  `email`
  * `password`
  * `birthdate`

Expected result:

```json
{
    "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjgsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODAwMC92MS9hdXRoL3JlZ2lzdGVyIiwiaWF0IjoxNTA2NDI3MTIxLCJleHAiOjE1MDY0MzA3MjEsIm5iZiI6MTUwNjQyNzEyMSwianRpIjoiWFc2SXRpRGhHUDhqbGJvciJ9.4aBnEQ-rxqlkDy2PcRPaPvOol_TSQCHNx1hut8OcBRo", 
    "token_type": "Bearer"
}
```
And basically the same for login, but changing the route to `/v1/auth/login `and only with **email** and **password**.

Expected result:
```json
{
    "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODAwMC92MS9hdXRoL2xvZ2luIiwiaWF0IjoxNTA2NDIyOTEwLCJleHAiOjE1MDY0MjY1MTAsIm5iZiI6MTUwNjQyMjkxMCwianRpIjoiMDlESU81aTVVcFY1RnQ5eSJ9.Zv9Fl1CMgObNdVqFYU231umygPNGhkB4SIKkKVOOGBE",
    "token_type": "bearer"    
}
```

## References
[API Wiki](https://github.com/doesangueorg/doesangue-core/wiki/API#authentication)
[API url](https://doesangueapi.herokuapp.com) (non oficial API. Created just for development)

### PR DESCRIPTION
**Pull request by miguejs**
### What this PR do?

* Add registration and login components, Closes #1 

_Please add Hacktober label to this PR please_

### CODE REVIEW

**Comment by miguejs** [comment]
@JoseCage  Done !

**Comment by JoseCage** [comment]
> @JoseCage Done !

Thanks @miguejs. I will merge it.. But i have tested it locally and nothing append before i `log in` for example..

**Comment by JoseCage** [comment]
Thanks for your contribution **BTW**..

**Comment by JoseCage** [comment]
@miguejs 
Login works fine (i think the problem with sign up comes from server, i will fix). But i see the the is being saved in localStorage with value `{"access_token": "$$$TOKEN_HERE", "token_type": Bearer"}`

full value (returned in my test): `{"access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEzLCJpc3MiOiJodHRwOi8vZG9lc2FuZ3VlYXBpLmhlcm9rdWFwcC5jb20vdjEvYXV0aC9sb2dpbiIsImlhdCI6MTUwNzczNjk2MSwiZXhwIjoxNTA3NzQwNTYxLCJuYmYiOjE1MDc3MzY5NjEsImp0aSI6IlhjM0tVQ0dqRW8wNG1jWWoifQ.0fwJ8W1pAZUV0PrP8oQp9bjdtymCwCM827ONZoD7JBY","token_type":"Bearer"}`

The expected value is only the `token` returned in response and in `Login` component you are saving all the response content as a **token** value..

**Comment by JoseCage** [comment]
I solved this already.. Thanks again @miguejs 

I have changed `Vue.localStorage.set('token', JSON.stringify(response.data))` to `Vue.localStorage.set('token', JSON.stringify(response.data.access_token))` inside the [login method](https://github.com/doesangueorg/doesangue-webapp/blob/development/src/components/auth/Login.vue#L28)

**Pull request merged**
